### PR TITLE
Add support for RFC2392 'mid:' URLs.

### PR DESCRIPTION
**Pull request by nbeaver**
Fixes https://github.com/mikehardy/thunderlink/issues/46

### CODE REVIEW

**Comment by nbeaver** [comment]
I've tested it with Thunderbird 68.7.0 on Ubuntu 18.04.4. I should probably also test it on Windows 10.

**Comment by mikehardy** [comment]
I don't see anything in it that should be windows-specific, if it works for you I'm sure it's good to go. Either way, it's a new branch of code which means it's sort of "opt-in" for usage as it did not even exist before, so no harm launching. It's already up on addons.thunderbird.net, thanks for the contribution :-)

**Comment by nbeaver** [comment]
You're welcome!

I think the registry file will have to be modified for the `mid` URLs to work on Windows.

**Comment by mikehardy** [comment]
Ah, you could be right there. If I recall @MarioKusek  uses Windows, he might know more?

**Comment by MarioKusek** [comment]
@mikehardy Sorry, I am on Mac

**Pull request merged**
